# Generated by Django 4.2.7 on 2023-11-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='fk_user',
        ),
    ]
