# Generated by Django 4.2.7 on 2023-11-30 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0002_remove_instance_fk_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openstack.authuser'),
        ),
    ]
